<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-M7GVVU2" failures="3" tests="6" name="Test2" time="0.753" errors="0" timestamp="2021-02-14T22:23:25 GMT-08:00">
  <testcase classname="com.qa.Tests.SampleTest" name="verifyUserAbleToLoginIn" time="0.039"/>
  <testcase classname="com.qa.Tests.SampleTest" name="verifyUserIsOnTheHomePage" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.Tests.SampleTest.verifyUserIsOnTheHomePage(SampleTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserIsOnTheHomePage -->
  <testcase classname="com.qa.Tests.SampleTest2" name="verifyUserAbleToLoginIn" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.Tests.SampleTest2.verifyUserAbleToLoginIn(SampleTest2.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserAbleToLoginIn -->
  <testcase classname="com.qa.Tests.SampleTest2" name="verifyUserIsOnTheHomePage" time="0.006"/>
  <testcase classname="com.qa.Tests.SampleTest3" name="verifyUserAbleToLoginIn" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.Tests.SampleTest3.verifyUserAbleToLoginIn(SampleTest3.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserAbleToLoginIn -->
  <testcase classname="com.qa.Tests.SampleTest3" name="verifyUserIsOnTheHomePage" time="0.003"/>
</testsuite> <!-- Test2 -->
